//home page

export default function Home() {
  return (
    <>
      <div className="container mx-auto px-4">
        <h1>Hello word</h1>
        <p>BIG FILLER BOX</p>
        <div className="w-full h-screen bg-gray-300"></div>
        <p>
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          BIG BOX BIG BOX BIG BOX BIG BOX
          
        </p>
      </div>
    </>
  );
}