name: Publish Docker image

on:
  push:
    branches: [ "main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: annix
  WEBAPP_NAME: AnnixDocker

jobs:

  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build
        run: |
          docker build -t annix --build-arg resendAPIKey=${{ secrets.RESEND_API_KEY }} --build-arg mongoURI=${{ secrets.MONGODB_URI }} --build-arg nextCloudName=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }} --build-arg blobConnectionString=${{ secrets.BLOB_CONNECTION_STRING }} . 
          docker tag annix ${{ secrets.DOCKER_USER}}/${{ env.IMAGE_NAME }}
          docker push ${{ secrets.DOCKER_USER}}/${{ env.IMAGE_NAME }}
          
  deploy_to_azure:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ env.IMAGE_NAME }}
