name: Publish Docker image

on:
  push:
    branches: [ "main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: annix
  WEBAPP_NAME: AnnixDocker

jobs:

  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./../../webapp/
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            resendAPIKey=${{ secrets.RESEND_API_KEY }}
            mongoURI=${{ secrets.MONGODB_URI }}
            nextCloudName=${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
            blobConnectionString=${{ secrets.BLOB_CONNECTION_STRING }}
            sendgridAPIKey=${{ secrets.SENDGRID_API_KEY }}
          
  deploy_to_azure:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKER_USER}}/${{ env.IMAGE_NAME }}'

  restart_azure:
    runs-on: ubuntu-latest
    needs: deploy_to_azure

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CRED }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            # az webapp stop --name ${{ env.WEBAPP_NAME }} --resource-group Annix
            # az webapp start --name ${{ env.WEBAPP_NAME }} --resource-group Annix
            az webapp restart --name ${{ env.WEBAPP_NAME }} --resource-group Annix
